// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvaiunpanqtibedkvyto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12YWl1bnBhbnF0aWJlZGt2eXRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNDIwMDUsImV4cCI6MjA1NTYxODAwNX0.FX-vf4GaZgADuG0cwqcAWQLH7Mj6seqE6e8rzJWPLZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);